name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug to BONELAB Fusion 5vs5!
  - type: dropdown
    id: Platform
    attributes:
      label: What platform did the bug appear on?
      multiple: true
      options:
        - PC
        - Quest Standalone
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug by giving clear and concise description of what the bug is. If applicable, outline the steps to reproduce the unwanted behavior and explain what was expected to happen instead. Screenshot and videos are welcome, too.
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (optional)
      render: shell
    validations:
      required: false
